# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ConfiguracionSistema.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import RecursosSTPUI_rc

class Ui_Configuracion(object):
    def setupUi(self, Configuracion):
        if not Configuracion.objectName():
            Configuracion.setObjectName(u"Configuracion")
        Configuracion.resize(1024, 600)
        Configuracion.setStyleSheet(u"background-color: rgb(150, 150, 150);")
        self.comboRescam = QComboBox(Configuracion)
        self.comboRescam.setObjectName(u"comboRescam")
        self.comboRescam.setGeometry(QRect(249, 400, 131, 27))
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboRescam.sizePolicy().hasHeightForWidth())
        self.comboRescam.setSizePolicy(sizePolicy)
        self.label = QLabel(Configuracion)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(50, 30, 130, 17))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label_2 = QLabel(Configuracion)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(50, 300, 130, 17))
        self.label_2.setFont(font)
        self.label_4 = QLabel(Configuracion)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(50, 520, 130, 17))
        self.label_4.setFont(font)
        self.label_5 = QLabel(Configuracion)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(50, 380, 130, 17))
        self.label_5.setFont(font)
        self.labelRescam = QLabel(Configuracion)
        self.labelRescam.setObjectName(u"labelRescam")
        self.labelRescam.setGeometry(QRect(60, 410, 70, 17))
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.labelRescam.sizePolicy().hasHeightForWidth())
        self.labelRescam.setSizePolicy(sizePolicy1)
        self.lineTiempo = QLineEdit(Configuracion)
        self.lineTiempo.setObjectName(u"lineTiempo")
        self.lineTiempo.setGeometry(QRect(250, 60, 131, 29))
        sizePolicy.setHeightForWidth(self.lineTiempo.sizePolicy().hasHeightForWidth())
        self.lineTiempo.setSizePolicy(sizePolicy)
        self.labelTiempo = QLabel(Configuracion)
        self.labelTiempo.setObjectName(u"labelTiempo")
        self.labelTiempo.setGeometry(QRect(60, 70, 130, 17))
        sizePolicy1.setHeightForWidth(self.labelTiempo.sizePolicy().hasHeightForWidth())
        self.labelTiempo.setSizePolicy(sizePolicy1)
        self.labelFPS = QLabel(Configuracion)
        self.labelFPS.setObjectName(u"labelFPS")
        self.labelFPS.setGeometry(QRect(60, 430, 131, 29))
        sizePolicy1.setHeightForWidth(self.labelFPS.sizePolicy().hasHeightForWidth())
        self.labelFPS.setSizePolicy(sizePolicy1)
        self.lineFPS = QLineEdit(Configuracion)
        self.lineFPS.setObjectName(u"lineFPS")
        self.lineFPS.setGeometry(QRect(249, 430, 131, 29))
        sizePolicy.setHeightForWidth(self.lineFPS.sizePolicy().hasHeightForWidth())
        self.lineFPS.setSizePolicy(sizePolicy)
        self.labellaser = QLabel(Configuracion)
        self.labellaser.setObjectName(u"labellaser")
        self.labellaser.setGeometry(QRect(60, 90, 130, 29))
        sizePolicy1.setHeightForWidth(self.labellaser.sizePolicy().hasHeightForWidth())
        self.labellaser.setSizePolicy(sizePolicy1)
        self.linelaser = QLineEdit(Configuracion)
        self.linelaser.setObjectName(u"linelaser")
        self.linelaser.setGeometry(QRect(250, 90, 131, 29))
        sizePolicy.setHeightForWidth(self.linelaser.sizePolicy().hasHeightForWidth())
        self.linelaser.setSizePolicy(sizePolicy)
        self.pushButton_2 = QPushButton(Configuracion)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(650, 330, 131, 41))
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.label_3 = QLabel(Configuracion)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(460, 340, 140, 17))
        sizePolicy1.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy1)
        self.labelResproy = QLabel(Configuracion)
        self.labelResproy.setObjectName(u"labelResproy")
        self.labelResproy.setGeometry(QRect(60, 540, 131, 27))
        sizePolicy1.setHeightForWidth(self.labelResproy.sizePolicy().hasHeightForWidth())
        self.labelResproy.setSizePolicy(sizePolicy1)
        self.comboResproy = QComboBox(Configuracion)
        self.comboResproy.setObjectName(u"comboResproy")
        self.comboResproy.setGeometry(QRect(250, 540, 131, 27))
        sizePolicy.setHeightForWidth(self.comboResproy.sizePolicy().hasHeightForWidth())
        self.comboResproy.setSizePolicy(sizePolicy)
        self.labelDistcam = QLabel(Configuracion)
        self.labelDistcam.setObjectName(u"labelDistcam")
        self.labelDistcam.setGeometry(QRect(60, 460, 161, 29))
        sizePolicy1.setHeightForWidth(self.labelDistcam.sizePolicy().hasHeightForWidth())
        self.labelDistcam.setSizePolicy(sizePolicy1)
        self.lineDistcam = QLineEdit(Configuracion)
        self.lineDistcam.setObjectName(u"lineDistcam")
        self.lineDistcam.setGeometry(QRect(250, 460, 131, 29))
        sizePolicy.setHeightForWidth(self.lineDistcam.sizePolicy().hasHeightForWidth())
        self.lineDistcam.setSizePolicy(sizePolicy)
        self.labelAnchoPantalla = QLabel(Configuracion)
        self.labelAnchoPantalla.setObjectName(u"labelAnchoPantalla")
        self.labelAnchoPantalla.setGeometry(QRect(60, 320, 141, 29))
        sizePolicy1.setHeightForWidth(self.labelAnchoPantalla.sizePolicy().hasHeightForWidth())
        self.labelAnchoPantalla.setSizePolicy(sizePolicy1)
        self.lineAnchoPantalla = QLineEdit(Configuracion)
        self.lineAnchoPantalla.setObjectName(u"lineAnchoPantalla")
        self.lineAnchoPantalla.setGeometry(QRect(250, 320, 131, 29))
        sizePolicy.setHeightForWidth(self.lineAnchoPantalla.sizePolicy().hasHeightForWidth())
        self.lineAnchoPantalla.setSizePolicy(sizePolicy)
        self.labelDisttir = QLabel(Configuracion)
        self.labelDisttir.setObjectName(u"labelDisttir")
        self.labelDisttir.setGeometry(QRect(60, 120, 180, 29))
        sizePolicy1.setHeightForWidth(self.labelDisttir.sizePolicy().hasHeightForWidth())
        self.labelDisttir.setSizePolicy(sizePolicy1)
        self.lineDisttir = QLineEdit(Configuracion)
        self.lineDisttir.setObjectName(u"lineDisttir")
        self.lineDisttir.setGeometry(QRect(250, 120, 131, 29))
        sizePolicy.setHeightForWidth(self.lineDisttir.sizePolicy().hasHeightForWidth())
        self.lineDisttir.setSizePolicy(sizePolicy)
        self.labelTiempoDisp = QLabel(Configuracion)
        self.labelTiempoDisp.setObjectName(u"labelTiempoDisp")
        self.labelTiempoDisp.setGeometry(QRect(60, 150, 161, 29))
        sizePolicy1.setHeightForWidth(self.labelTiempoDisp.sizePolicy().hasHeightForWidth())
        self.labelTiempoDisp.setSizePolicy(sizePolicy1)
        self.lineTiempoDisp = QLineEdit(Configuracion)
        self.lineTiempoDisp.setObjectName(u"lineTiempoDisp")
        self.lineTiempoDisp.setGeometry(QRect(250, 150, 131, 29))
        sizePolicy.setHeightForWidth(self.lineTiempoDisp.sizePolicy().hasHeightForWidth())
        self.lineTiempoDisp.setSizePolicy(sizePolicy)
        self.labelCantPulsos = QLabel(Configuracion)
        self.labelCantPulsos.setObjectName(u"labelCantPulsos")
        self.labelCantPulsos.setGeometry(QRect(60, 180, 161, 29))
        sizePolicy1.setHeightForWidth(self.labelCantPulsos.sizePolicy().hasHeightForWidth())
        self.labelCantPulsos.setSizePolicy(sizePolicy1)
        self.lineCantPulsos = QLineEdit(Configuracion)
        self.lineCantPulsos.setObjectName(u"lineCantPulsos")
        self.lineCantPulsos.setGeometry(QRect(250, 180, 131, 29))
        sizePolicy.setHeightForWidth(self.lineCantPulsos.sizePolicy().hasHeightForWidth())
        self.lineCantPulsos.setSizePolicy(sizePolicy)
        self.labelEscala = QLabel(Configuracion)
        self.labelEscala.setObjectName(u"labelEscala")
        self.labelEscala.setGeometry(QRect(60, 210, 131, 29))
        sizePolicy1.setHeightForWidth(self.labelEscala.sizePolicy().hasHeightForWidth())
        self.labelEscala.setSizePolicy(sizePolicy1)
        self.lineEscala = QLineEdit(Configuracion)
        self.lineEscala.setObjectName(u"lineEscala")
        self.lineEscala.setGeometry(QRect(250, 210, 131, 29))
        sizePolicy.setHeightForWidth(self.lineEscala.sizePolicy().hasHeightForWidth())
        self.lineEscala.setSizePolicy(sizePolicy)
        self.comboVisible = QComboBox(Configuracion)
        self.comboVisible.setObjectName(u"comboVisible")
        self.comboVisible.setGeometry(QRect(250, 240, 131, 27))
        sizePolicy.setHeightForWidth(self.comboVisible.sizePolicy().hasHeightForWidth())
        self.comboVisible.setSizePolicy(sizePolicy)
        self.label_6 = QLabel(Configuracion)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(460, 150, 161, 17))
        sizePolicy1.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy1)
        self.label_7 = QLabel(Configuracion)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(450, 30, 130, 17))
        self.label_7.setFont(font)
        self.label_8 = QLabel(Configuracion)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(650, 150, 101, 17))
        sizePolicy1.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy1)
        self.label_9 = QLabel(Configuracion)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(650, 180, 121, 17))
        sizePolicy1.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy1)
        self.lineEdit = QLineEdit(Configuracion)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(800, 140, 71, 29))
        self.lineEdit_2 = QLineEdit(Configuracion)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(800, 170, 71, 29))
        self.line = QFrame(Configuracion)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(460, 300, 410, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.pushButton_4 = QPushButton(Configuracion)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(650, 240, 131, 41))
        self.label_10 = QLabel(Configuracion)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(460, 360, 140, 17))
        sizePolicy1.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy1)
        self.label_11 = QLabel(Configuracion)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(460, 70, 171, 17))
        sizePolicy1.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy1)
        self.pushButton_5 = QPushButton(Configuracion)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(650, 60, 221, 41))
        font1 = QFont()
        font1.setBold(True)
        font1.setWeight(75)
        self.pushButton_5.setFont(font1)
        self.pushButton_5.setStyleSheet(u"background-color: rgb(0, 180, 0);")
        self.line_3 = QFrame(Configuracion)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(460, 110, 410, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.pushGuardar = QPushButton(Configuracion)
        self.pushGuardar.setObjectName(u"pushGuardar")
        self.pushGuardar.setGeometry(QRect(650, 520, 221, 51))
        self.pushGuardar.setFont(font1)
        self.pushGuardar.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.pushButton_7 = QPushButton(Configuracion)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(800, 240, 71, 40))
        self.pushButton_8 = QPushButton(Configuracion)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(800, 330, 71, 41))
        self.label_12 = QLabel(Configuracion)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(650, 210, 121, 17))
        sizePolicy1.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy1)
        self.lineEdit_3 = QLineEdit(Configuracion)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(800, 200, 71, 29))
        self.pushButton = QPushButton(Configuracion)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(1000, 0, 20, 20))
        self.pushButton.setStyleSheet(u"")
        icon = QIcon()
        icon.addFile(u":/Imagnes MainSTP/MyIconos/window-close-regular.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QSize(20, 20))
        self.labelEscala_2 = QLabel(Configuracion)
        self.labelEscala_2.setObjectName(u"labelEscala_2")
        self.labelEscala_2.setGeometry(QRect(60, 240, 131, 29))
        sizePolicy1.setHeightForWidth(self.labelEscala_2.sizePolicy().hasHeightForWidth())
        self.labelEscala_2.setSizePolicy(sizePolicy1)

        self.retranslateUi(Configuracion)
        self.pushButton.clicked.connect(Configuracion.close)

        QMetaObject.connectSlotsByName(Configuracion)
    # setupUi

    def retranslateUi(self, Configuracion):
        Configuracion.setWindowTitle(QCoreApplication.translate("Configuracion", u"Configuracion General", None))
        self.label.setText(QCoreApplication.translate("Configuracion", u"Sistema", None))
        self.label_2.setText(QCoreApplication.translate("Configuracion", u"Pantalla", None))
        self.label_4.setText(QCoreApplication.translate("Configuracion", u"Proyector", None))
        self.label_5.setText(QCoreApplication.translate("Configuracion", u"Camara", None))
        self.labelRescam.setText(QCoreApplication.translate("Configuracion", u"Resolucion", None))
        self.labelTiempo.setText(QCoreApplication.translate("Configuracion", u"Tiempo de Exposicion", None))
        self.labelFPS.setText(QCoreApplication.translate("Configuracion", u"Cuadros por Segundo", None))
        self.labellaser.setText(QCoreApplication.translate("Configuracion", u"T_Laser [us]", None))
        self.pushButton_2.setText(QCoreApplication.translate("Configuracion", u"Captura Continua", None))
        self.label_3.setText(QCoreApplication.translate("Configuracion", u"Captura continua ", None))
        self.labelResproy.setText(QCoreApplication.translate("Configuracion", u"Resolucion", None))
        self.labelDistcam.setText(QCoreApplication.translate("Configuracion", u"Distancia Camara-Proyector", None))
        self.labelAnchoPantalla.setText(QCoreApplication.translate("Configuracion", u"Ancho Pantalla [m]", None))
        self.labelDisttir.setText(QCoreApplication.translate("Configuracion", u"Distancia Tirador - Pantalla [m]", None))
        self.labelTiempoDisp.setText(QCoreApplication.translate("Configuracion", u"Tiempo entre disparos [ms]", None))
        self.labelCantPulsos.setText(QCoreApplication.translate("Configuracion", u"Cant. Pulsos disparo falso", None))
        self.labelEscala.setText(QCoreApplication.translate("Configuracion", u"Escala Resultado", None))
        self.label_6.setText(QCoreApplication.translate("Configuracion", u"Presentacion Cuadricula", None))
        self.label_7.setText(QCoreApplication.translate("Configuracion", u"Asistentes", None))
        self.label_8.setText(QCoreApplication.translate("Configuracion", u"Puntos en X", None))
        self.label_9.setText(QCoreApplication.translate("Configuracion", u"Diametro de puntos", None))
        self.pushButton_4.setText(QCoreApplication.translate("Configuracion", u"Proyectar cuadricula", None))
        self.label_10.setText(QCoreApplication.translate("Configuracion", u"de la camara", None))
        self.label_11.setText(QCoreApplication.translate("Configuracion", u"Calibracion Camara-Proyector", None))
        self.pushButton_5.setText(QCoreApplication.translate("Configuracion", u"Calibracion Automatica", None))
        self.pushGuardar.setText(QCoreApplication.translate("Configuracion", u"Guardar Configuracion", None))
        self.pushButton_7.setText(QCoreApplication.translate("Configuracion", u"Salir", None))
        self.pushButton_8.setText(QCoreApplication.translate("Configuracion", u"Salir", None))
        self.label_12.setText(QCoreApplication.translate("Configuracion", u"Ancho borde", None))
        self.pushButton.setText("")
        self.labelEscala_2.setText(QCoreApplication.translate("Configuracion", u"Cantidad de Tiradores", None))
    # retranslateUi

